version: '3.3'
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        networks:
            - db_nw
    web:
        build: .
        restart: always
        command: bash -c "flask db upgrade && gunicorn app:app --name canary_homework --bind 0.0.0.0:5000 --workers 1 --log-level=info --log-file=/logs/gunicorn.log --access-logfile=/logs/gunicorn-access.log"
        environment:
            - APP_SETTINGS=config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:password@db/postgres
        depends_on:
            - db
        volumes:
            - ./logs:/logs
        networks:
            - db_nw
            - web_nw
    nginx:
        image: "nginx:1.13.5"
        ports:
            - "5000:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - web
        networks:
            - web_nw
networks:
    db_nw:
        driver: bridge
    web_nw:
        driver: bridge
