"""empty message

Revision ID: 570220dd8d64
Revises: 
Create Date: 2018-03-24 21:48:18.703958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570220dd8d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_samples',
    sa.Column('device_uuid', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=False),
    sa.Column('sensor_reading_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('device_uuid', 'sensor_type', 'sensor_value', 'sensor_reading_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_samples')
    # ### end Alembic commands ###
